[package]
name = "two_percent"
version = "0.10.30"
authors = ["Zhang Jinzhou <lotabout@gmail.com>", "Robert Swinford <robert.swinford <...at...> gmail.com>"]
description = "Fuzzy Finder in rust!"
documentation = "https://docs.rs/skim"
homepage = "https://github.com/kimono-koans/two_percent"
repository = "https://github.com/kimono-koans/two_percent"
readme  = "README.md"
keywords = ["fuzzy", "menu", "util"]
license = "MIT"
edition = "2018"

[lib]
name = "skim"
path = "src/lib.rs"

[[bin]]
name = "sk"
path = "src/bin/main.rs"

[dependencies]
nix = { version = "0.27.1", default-features = false }
atty = { version = "0.2.14", optional = true }
regex = { version = "1.10.2", features = ["unicode-perl"] }
lazy_static = { version = "1.4.0", default-features = false }
shlex = { version = "1.2.0", optional = true, default-features = false }
unicode-width = { version = "0.1.11", default-features = false }
log = { version = "0.4.20", default-features = false }
env_logger = { version = "0.10.1", optional = true }
time = { version = "0.3.21", default-features = false }
clap = { version = "3.2.25", optional = true, features = ["cargo"] }
tuikit = { version = "0.5.0", default-features = false }
vte = { version = "0.13.0", default-features = false }
fuzzy-muff = { version = "0.3.10", default-features = false }
rayon = { version = "1.8.0",  default-features = false }
derive_builder = { version = "0.12.0", default-features = false }
bitflags = { version = "2.4.1", default-features = false }
timer = { version = "0.2.0", default-features = false }
chrono = { version = "0.4.31", default-features = false }
crossbeam-channel = { version = "0.5.8", default-features = false, features = ["std"] }
defer-drop = { version = "1.3.0", default-features = false }
libc = { version = "0.2.150", default-features = false }

[patch.crates-io]
timer = { git = "https://github.com/kimono-koans/timer.rs" }

[features]
default = ["cli"]
cli = ["dep:clap", "dep:atty", "dep:shlex", "dep:env_logger"]

[profile.release]
debug = false